version: "3.5"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - ./backend/.env
    networks:
    - backend_network
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - ./backend/.env
    networks:
    - backend_network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3007:3007"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - backend_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4000:4000"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
